name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: cachix/install-nix-cation@v7
  - uses: cachix/cachix-action@v4
    with:
        name: kalhauge
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
